import {
  Activity,
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  Barcode,
  Bell,
  Boxes,
  Building2,
  Calendar,
  ChartPie,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CirclePlus,
  CircleQuestionMark,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CommandIcon,
  CreditCard,
  Download,
  File,
  FileSearch,
  FileText,
  Folder,
  Gift,
  Heart,
  Home,
  Info,
  Landmark,
  Laptop,
  LayersIcon,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Loader2,
  LogOut,
  Maximize,
  Medal,
  Menu,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  PackagePlus,
  PackageX,
  Pause,
  Pencil,
  Percent,
  Play,
  Plus,
  QrCode,
  Receipt,
  RefreshCw,
  Ruler,
  Scale,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Square,
  Star,
  Store,
  Tags,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCheck,
  Users,
  UserX,
  Volume2,
  Warehouse,
  X,
} from 'lucide-react';

import { CustomCircleIcon } from './custom-icons/circle';
import { CustomExpiredIcon } from './custom-icons/expired';
import type { TIcon, TIconName } from './icon.types';

export const IconMap: Record<TIconName, TIcon> = {
  // ===== Navigation =====
  home: Home,
  menu: Menu,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,

  // ===== Actions =====
  search: Search,
  close: X,
  plus: Plus,
  circlePlus: CirclePlus,
  minus: Minus,
  check: Check,
  edit: Pencil,
  trash: Trash2,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  command: CommandIcon,
  maximize: Maximize,

  // ===== Status =====
  info: Info,
  warning: CircleAlert,
  error: AlertCircle,
  success: CheckCircle,
  loader: Loader2,

  // ===== Media =====
  play: Play,
  pause: Pause,
  stop: Square,
  volume: Volume2,

  // ===== User =====
  user: User,
  users: Users,
  settings: Settings,
  logOut: LogOut,

  // ===== Files =====
  file: File,
  folder: Folder,
  fileText: FileText,

  // ===== Misc =====
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  star: Star,
  heart: Heart,
  laptop: Laptop,
  layers: LayersIcon,
  chartPie: ChartPie,

  // ===== Sidebar =====
  layoutDashboard: LayoutDashboard,
  shieldCheck: ShieldCheck,
  package: Package,
  createProduct: PackagePlus,
  expired: CustomExpiredIcon,
  lowStock: TrendingDown,
  category: LayoutGrid,
  subCategory: LayersIcon,
  brands: Award,
  units: Ruler,
  variantAttributes: SlidersHorizontal,
  warranties: BadgeCheck,
  printBarcode: Barcode,
  printQrCode: QrCode,
  tags: Tags,
  barcode: Barcode,
  boxes: Boxes,
  shoppingCart: ShoppingCart,
  receipt: Receipt,
  shoppingBag: ShoppingBag,
  percent: Percent,
  creditCard: CreditCard,
  store: Store,
  warehouse: Warehouse,
  barChart: BarChart3,

  // ===== Stock =====
  stockAdjustment: ArrowUpDown,
  stockTransfer: ArrowLeftRight,

  // ===== Promo =====
  coupons: Ticket,
  giftCard: Gift,

  // ===== Purchases =====
  purchaseOrder: ClipboardList,
  purchaseReturn: PackageX,

  // ===== Finance =====
  income: TrendingUp,
  bankAccount: Landmark,
  moneyTransfer: ArrowLeftRight,
  balanceSheet: Scale,
  trialBalance: FileSearch,
  cashFlow: Activity,
  accountStatement: ScrollText,

  // ===== Peoples =====
  billers: UserCheck,
  suppliers: Truck,

  // ===== HRM =====
  departments: Building2,
  designation: Medal,
  shifts: Clock,
  attendance: ClipboardCheck,
  leaves: Leaf,
  holidays: Calendar,
  payroll: Banknote,

  // ===== User Management =====
  rolesPermissions: ShieldCheck,
  deleteRequest: UserX,

  // ===== Custom =====
  circle: CustomCircleIcon,

  // ===== Fallback =====
  default: CircleQuestionMark,
};
